# this workflow should deploy some production env
name: Production

on:
  workflow_dispatch:
  push:
    tags:
      - v*

concurrency:
  cancel-in-progress: true
  group: production

jobs:
  # Todo: only produce matrix for relevant functions
  init:
    runs-on: ubuntu-latest
    name: Prepare
    outputs:
      functions: ${{ steps.init.outputs.functions }}
    steps:
      - uses: actions/checkout@v3
      - id: init
        uses: ./.github/actions/list-functions

  ##############################################################################
  ## BUILD AND REGISTER DOCKER IMAGES
  ##############################################################################
  register:
    name: Build & Register functions
    runs-on: ubuntu-latest
    needs: init
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        function: ${{ fromJson(needs.init.outputs.functions) }}
    steps:
      - uses: actions/checkout@v3
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: "prod"
          token: ${{ secrets.GITHUB_TOKEN }}
          imageName: sre-faas/${{ matrix.function }}
          dockerbuildargs: |
            FUNCTION=${{ matrix.function }}

  ##############################################################################
  ## DEPLOPY APPLICATION
  ##############################################################################
  deploy:
    name: Deploy functions
    runs-on: ubuntu-latest
    needs: [init, register]
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        function: ${{ fromJson(needs.init.outputs.functions) }}
    environment:
      name: production
    steps:
      - name: Use autodevops deployment
        uses: SocialGouv/kube-workflow@v1
        with:
          environment: "prod"
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
          rancherProjectName: ${{ secrets.RANCHER_PROJECT_NAME }}
          charts: app-${{ matrix.function }}
          inlineValues: |
            global:
              namespace: sre-faas-${{ matrix.function }}
          actionName: ${{ matrix.function }}
