# this workflow should deploy some production env
name: Production

on:
  push:
    tags:
      - v*

concurrency:
  cancel-in-progress: true
  group: prod-${{ github.ref }}

jobs:
  # Todo: only produce matrix for relevant functions
  init:
    runs-on: ubuntu-latest
    name: Prepare
    outputs:
      functions: ${{ steps.init.outputs.functions }}
    steps:
      - uses: actions/checkout@v2
      - id: init
        uses: ./.github/actions/list-functions

  ##############################################################################
  ## BUILD AND REGISTER DOCKER IMAGES
  ##############################################################################
  register:
    name: Build & Register functions
    runs-on: ubuntu-latest
    needs: init
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        functions: ${{ fromJson(needs.init.outputs.functions) }}
    steps:
      - uses: actions/checkout@v2
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: "prod"
          token: ${{ secrets.GITHUB_TOKEN }}
          imageName: sre-faas/${{ matrix.functions }}
          dockerbuildargs: |
            FUNCTION=${{ matrix.functions }}

  ##############################################################################
  ## DEPLOPY APPLICATION
  ##############################################################################
  deploy:
    name: Deploy functions
    runs-on: ubuntu-latest
    needs: [init, register]
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        functions: ${{ fromJson(needs.init.outputs.functions) }}
    environment:
      name: production
    steps:
      - name: Use autodevops deployment
        uses: SocialGouv/actions/autodevops-helm-deploy@v1
        with:
          environment: prod
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
          imageName: sre-faas/${{ matrix.functions }}
          baseNamespace: sre-faas-${{ matrix.functions }}
          baseSubdomain: sre-faas-${{ matrix.functions }}
          basePath: functions/${{ matrix.functions }}
          deploymentName: sre-faas-${{ matrix.functions }}
