# this workflow should do a single release for all packages

name: Release

on:
  workflow_dispatch:
  # push:
  #   branches-ignore:
  #     - master
  #   tags-ignore:
  #     - v*

jobs:
  init:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          echo "plop"
