# this workflow should do a single release for all packages

name: Test

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - v*

jobs:
  init:
    runs-on: ubuntu-latest
    name: Prepare
    outputs:
      functions: ${{ steps.init.outputs.functions }}
    steps:
      - uses: actions/checkout@v2
      - id: init
        shell: bash
        run: |
          FUNCTIONS=$(ls -l functions | awk '/^d/ {print $9}')
          echo $FUNCTIONS
          echo "::set-output name=functions::$FUNCTIONS"

  ##############################################################################
  ## BUILD AND REGISTER DOCKER IMAGES
  ##############################################################################
  register:
    name: Build & Register functions
    runs-on: ubuntu-latest
    needs: init
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        functions: ${{ fromJson(needs.init.outputs.functions) }}
    steps:
      - uses: actions/checkout@v2
      - name: Test ${{ matrix.functions }}
        shell: bash
        run: |
          cd functions/${{ matrix.functions }}
          yarn
          yarn test
